// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcYS0hJnW_rrVzCM6AiK_noxvvd0SGQSc',
    appId: '1:802129841566:web:259e10922db259f3bcda8f',
    messagingSenderId: '802129841566',
    projectId: 'mynotes-49507',
    authDomain: 'mynotes-49507.firebaseapp.com',
    storageBucket: 'mynotes-49507.appspot.com',
    measurementId: 'G-ZF0VBV81XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0qrlQiglc7LArWyfU1CSOJWpEEwvPk1Q',
    appId: '1:802129841566:android:52195cecfd19c3adbcda8f',
    messagingSenderId: '802129841566',
    projectId: 'mynotes-49507',
    storageBucket: 'mynotes-49507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA74eueitKut7U1lwb-1hSnIgou8uolvA',
    appId: '1:802129841566:ios:45255b640cfbf3c7bcda8f',
    messagingSenderId: '802129841566',
    projectId: 'mynotes-49507',
    storageBucket: 'mynotes-49507.appspot.com',
    iosBundleId: 'com.hari-pace-practice.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA74eueitKut7U1lwb-1hSnIgou8uolvA',
    appId: '1:802129841566:ios:a0844edea7f30b70bcda8f',
    messagingSenderId: '802129841566',
    projectId: 'mynotes-49507',
    storageBucket: 'mynotes-49507.appspot.com',
    iosBundleId: 'com.hari-pace-practice.mynotes.RunnerTests',
  );
}
